sonar.projectKey=cristianfoltis_autolog
sonar.organization=cristianfoltis
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.cpd.exclusions=**/*.test.*
sonar.exclusions=frontend/src/App.tsx,frontend/src/main.tsx,frontend/src/types/auth.types.ts,frontend/src/router/index.tsx,frontend/src/pages/AuthCallbackPage.tsx,frontend/src/pages/DashboardPage.tsx,backend/src/prisma/client.ts,backend/src/config/passport.ts,backend/src/types/express.d.ts